---
# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
include:
  - project: ednz-cloud/gitlab-ci-library
    ref: main
    file: includes/pypi-publish.yml
    inputs:
      stage: publish
      publish_index: ednz-cloud
      rules:
        - if: $CI_COMMIT_TAG
